### ISSUE TITLE
Xenial: Disable unattended apt upgrade

### ISSUE THREAD

**Issue by joepvd** [travis-ci/travis-cookbooks#952]
`sudo apt-get install` fails on a Xenial image with the error: `Could not get lock /var/lib/dpkg/lock`.

It turns out that a daily job is running unattended upgrades in the background:

https://travis-ci.org/joepvd/travis-experiment/builds/307805100#L608

This should be disabled.

**Comment by pkgw** [comment]
See [this StackExchange post](https://unix.stackexchange.com/questions/315502/how-to-disable-apt-daily-service-on-ubuntu-cloud-vm-image) for an analysis of solutions in a similar situation. Presumably Travis could create images that disabled the updater service entirely, though.

**Comment by meatballhat** [comment]
Addressed by #973 :tada:

**Comment by StuntsPT** [comment]
I am not sure if #973 has already been deployed, but I am still experiencing this issue, [here](https://travis-ci.org/StuntsPT/pyRona/jobs/376572003).
